# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: ftps-control-service
  namespace: default
spec:
  selector:
    app: server
  type: NodePort
  ports:
  - name: ftps-control-service
    protocol: TCP
    port: 990
    targetPort: 7002
    nodePort: 30990
  sessionAffinity: ClientIP
---

