# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: ftps-data-service
  namespace: default
spec:
  selector:
    app: server
  type: NodePort
  ports:
  - name: ftps-data-service
    protocol: TCP
    port: 989
    targetPort: 7001
    nodePort: 30989
  sessionAffinity: ClientIP
---

