# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  namespace: default
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
  - name: ftps-control
    protocol: TCP
    port: 7002
    targetPort: 7002
  - name: ftps-data
    protocol: TCP
    port: 7001
    targetPort: 7001
  sessionAffinity: ClientIP
---

