apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server
spec:
  securityContext:
    runAsUser: 0

  containers:
  - name: server
    image: ongtsingiok/secure-cloud-server:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8443
    volumeMounts:
    - name: config-volume
      mountPath: "/usr/src/app/config"
      readOnly: true
    - name: secret-volume
      mountPath: "/usr/src/app/data/certs"
      readOnly: true
    - name: wallet-volume
      mountPath: "/usr/src/app/data/wallet"
    - name: data-volume
      mountPath: "/usr/src/app/data"
  volumes:
    - name: config-volume
      configMap:
        name: server-config
    - name: secret-volume
      secret:
        secretName: server-tls-secret
    - name: wallet-volume
      secret:
        secretName: wallet-secret
    - name: data-volume
      persistentVolumeClaim:
        claimName: test-pv-claim
