apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server
spec:
  # securityContext:
  #   runAsUser: 0

  containers:
  - name: server
    image: ongtsingiok/secure-cloud-server:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 3001
    - containerPort: 7001
    - containerPort: 7002
    volumeMounts:
    - name: config-volume
      mountPath: "/usr/src/app/config"
      readOnly: true
    - name: secret-volume
      mountPath: "/usr/src/app/certs"
      readOnly: true
    - name: blockchain-volume
      mountPath: "/usr/src/app/blockchain"
    - name: data-volume
      mountPath: "/usr/src/app/data"
  volumes:
    - name: config-volume
      configMap:
        name: server-config
    - name: secret-volume
      secret:
        secretName: server-tls-secret
    - name: blockchain-volume
      projected:
        sources:
        - secret:
          secretName: wallet-secret
        - configMap:
          name: contract-abi
    - name: data-volume
      persistentVolumeClaim:
        claimName: local-path-pvc
