# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: https-service
  namespace: default
spec:
  selector:
    app: server
  type: NodePort
  ports:
  - name: https-service
    protocol: TCP
    port: 443
    targetPort: 8443
    nodePort: 30001
---

