directories:
  uploads: uploads
  certs: certs
  logs: logs
  database: database
  blockchain: blockchain
  ssh: ssh
server:
  host: 0.0.0.0
  key: tls.key
  cert: tls.crt
  https:
    port: 3001
  ftps:
    port:
      control: 7002
      data: 7000
    pasv_url: 'localhost:7000'
  ssh:
    key: id_ed25519
  sftp:
    port: 7001
database:
  user: postgres
  host: localhost
  database: postgres
  password: postgres
  port: 5432
  pool:
    max: 20
    idleTimeoutMillis: 30000
    connectionTimeoutMillis: 2000
  ssl:
    rejectUnauthorized: true
  descMaxLength: 2000
  # null values will be seen as the same as global settings
  secretShare:
  - user: null
    host: null
    database: secret_share1
    password: null
    port: null
  - user: null
    host: null
    database: secret_share2
    password: null
    port: null
  - user: null
    host: null
    database: secret_share3
    password: null
    port: null
loginAttempts:
  limit: 5
  timeout: 15 # In minutes
blockchain:
  jsonRpcUrl: ''
  contractAddr: ''
  walletKeyPath: wallet.key
  abiPath: abi.json
  enabled: true
settings:
  uploadExpireTimeMin: 10
  emailAuthExpireTimeMin: 5
  emailAuthLength: 6
trustedAuthority:
  url: 'localhost:2999'